version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: 'Europe/Lisbon'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Europe/Lisbon'
      SERVERURL: 'vera.dynip.sapo.pt' #optional
      SERVERPORT: '51820' #optional
      PEERS: '10' #optional
      PEERDNS: '192.168.1.101' #optional
      INTERNAL_SUBNET: '172.19.1.0' #optional
    volumes:
      - './wireguard/config:/config'
      - './wireguard/wireguard:/etc/wireguard'
      - '/lib/modules:/lib/modules'
    ports:
      - 51820:51820/udp
      - 51820:51820/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
